name: Push to master

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - name: Set Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Set NPM Registry identity
        uses: ohoareau/actions/npmrc-scope-authtoken-add@master
        with:
          scope: ohoareau
          token: ${{secrets.CUSTOM_NPM_TOKEN}}
          registry: registry.npmjs.org

      - name: Set Env from current Branch
        uses: ohoareau/actions/branch-to-env@master
        with:
          secrets: ${{toJson(secrets)}}
          branch: ${{github.base_ref}}

      - name: Install
        shell: 'script -q -e -c "bash {0}"'
        run: make install
        env:
          FORCE_COLOR: 3
          CI: true

      - name: Test
        shell: 'script -q -e -c "bash {0}"'
        run: make test
        env:
          FORCE_COLOR: 3
          CI: true
